#ifndef AURORA_ARCH_V1_2_H
#define AURORA_ARCH_V1_2_H

#define AURORA_REG_COUNT 16
#define AURORA_ISSUE_WIDTH 2
#define AURORA_WINDOW_ENTRIES 4
#define AURORA_INTERRUPT_LEVELS 16

typedef enum {
    AURORA_MODE_SCALAR32 = 0,
    AURORA_MODE_PACKED16 = 1,
    AURORA_MODE_PACKED8 = 2,
    AURORA_MODE_LOW16 = 3,
    AURORA_MODE_LOW8 = 4,
    AURORA_MODE_PAIRED64 = 5,
} aurora_mode_t;

#endif