"""Auto-generated Aurora v1.2 architecture constants."""
REGISTER_COUNT = 16
ISSUE_WIDTH = 2
WINDOW_ENTRIES = 4
INTERRUPT_LEVELS = 16
MODES = {
  "SCALAR32": 0,
  "PACKED16": 1,
  "PACKED8": 2,
  "LOW16": 3,
  "LOW8": 4,
  "PAIRED64": 5
}
EXCEPTIONS = {
  "ILLEGAL_INSTRUCTION": 0,
  "ALIGNMENT_FAULT": 1,
  "ACCESS_FAULT": 2,
  "PRIVILEGE_FAULT": 3,
  "DIVIDE_BY_ZERO": 4,
  "SIGNED_DIV_OVERFLOW": 5,
  "BREAKPOINT": 6,
  "EXTERNAL_BUS_FAULT": 7
}